### ISSUE TITLE
Correct way to set metro.config.js

### ISSUE THREAD

**Issue by bluenex** [kristerkari/react-native-svg-transformer#141]
I added this library to the project long ago when there wasn't `metro.config.js` file. I have just noticed when I upgraded React Native to version 0.64.1 that the `metro.config.js` is added to the `create-react-native-app`. So the file looks somethings like this:

```js
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

and `metro.config.js` to use this library looks like this:

```js
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

so what I think the correct way to merge them together is something like this:

```js
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

But this **doesn't** work for me. It does build successfully, however, the screen is blank after the splash screen is gone. What works for me (the screen is not blank after staring up) is this:

```js
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      experimentalImportSupport: false,
      inlineRequires: true,
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

But I'm not sure this is the correct way to paste those keys (`experimentalImportSupport`, `inlineRequires`).

**Comment by rvieceli** [comment]
@bluenex I used like your second example with one change, passing `__dirname` to `getDefaultConfig`.
```js
await getDefaultConfig(__dirname)
```

**Comment by pangolingo** [comment]
Using the recommended config, I encountered an error when using the `expo-asset` library. Expo Asset expects an `assetPlugins` transformer. Without it, there are no errors, but images don't show up in iOS release builds.

I fixed it by adding the assetPlugins config. Figured I would mention it here because it might be worth documenting.

Original `metro.config.js` (based on this library's documentation):

```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

// extra config is needed to enable `react-native-svg-transformer`
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig(__dirname);
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

Updated config to support Expo Assets:

```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

// extra config is needed to enable `react-native-svg-transformer`
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig(__dirname);
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      assetPlugins: ['expo-asset/tools/hashAssetFiles'],
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();

```

This line was added:
`assetPlugins: ['expo-asset/tools/hashAssetFiles'],`

**Comment by dpolivy** [comment]
I was running into a few issues with the `metro.config.js` promoted in the README and our Expo app, so wanted to report back here with my experiences and resolution. We recently upgraded to Expo SDK 42 and EAS Build. With the recommended config in the README, I'd get this warning when trying to do a build:

````
It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config.
This can result in unexpected and hard to debug issues, like missing assets in the production bundle.
We recommend you to abort, fix the metro.config.js, and try again.
````

This is fixed, as others mentioned above, by adding the `assetPlugins` prop to `transformer` -- however, if this prop is missing, there may be others there that are missing as well. Here's my modified `metro.config.js` which simply merges in the SVG fields into the existing config in the method documented by Expo in [Customizing Metro](https://docs.expo.dev/guides/customizing-metro/).

I was also having issues with iOS builds not including assets, and I can now happily report this is resolved using the config below. Perhaps it's time to update the README in this project with a new example?

````
const {getDefaultConfig} = require('expo/metro-config');

module.exports = (async () => {
    const config = await getDefaultConfig(__dirname);

    const {transformer, resolver} = config;

    config.transformer = {
        ...transformer,
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
    };
    config.resolver = {
        ...resolver,
        assetExts: resolver.assetExts.filter(ext => ext !== 'svg'),
        sourceExts: [...resolver.sourceExts, 'svg'],
    };

    return config;
})();
````

**Comment by MalekBouba** [comment]
I encountered the same issue, and as the warning said, it fails my android build, but, only when using:
```
eas build -p android ...
```
but, not with
```
expo build:android ...
```
anyway, @dpolivy solution removed the warning but it doesn't fix the build.
error:
```
> Task :react-native-async-storage_async-storage:compileReleaseJavaWithJavac
[stderr] /root/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java:27: error: package com.facebook.react.module.annotations does not exist
[stderr] import com.facebook.react.module.annotations.ReactModule;
[stderr]                                             ^
[stderr] /root/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java:35: error: cannot find symbol
[stderr] @ReactModule(name = AsyncStorageModule.NAME)
[stderr]  ^
[stderr]   symbol: class ReactModule
[stderr] Note: /root/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
[stderr] Note: Recompile with -Xlint:deprecation for details.
[stderr] Note: /root/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
[stderr] Note: Recompile with -Xlint:unchecked for details.
[stderr] 2 errors
> Task :react-native-async-storage_async-storage:compileReleaseJavaWithJavac FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':react-native-async-storage_async-storage:compileReleaseJavaWithJavac'.
[stderr] > Compilation failed; see the compiler error output for details.
```
The standalone build still working.

**Comment by mersiades** [comment]
I'm having similar problems with `eas build -p ios` and `eas build -p android`.

@dpolivy 's solution gets rid of the warning and allows the build to start, but then it fails in the fastlane stage.

Android: 
```
[stderr] /root/workingdir/build/node_modules/expo/android/build/generated/expo/src/main/java/expo/modules/ExpoModulesPackageList.java:6: error: package expo.modules.kotlin.modules does not exist
957
[stderr] import expo.modules.kotlin.modules.Module;
```

iOS:
```

❌  (ios/Pods/Target Support Files/Pods-[redacted]/ExpoModulesProvider.swift:19:56)

  17 |   }
  18 | 
> 19 |   public override func getAppDelegateSubscribers() -> [ExpoAppDelegateSubscriber.Type] {
     |                                                        ^ cannot find type 'ExpoAppDelegateSubscriber' in scope
  20 |     return [
  21 |     ]
  22 |   }
974

❌  (ios/Pods/Target Support Files/Pods-[redacted]/ExpoModulesProvider.swift:19:24)

  17 |   }
  18 | 
> 19 |   public override func getAppDelegateSubscribers() -> [ExpoAppDelegateSubscriber.Type] {
     |                        ^ method does not override any method from its superclass
  20 |     return [
  21 |     ]
  22 |   }
```

I've tried the two solutions on PR #151, but they both failed locally.

I've got no idea how to fix this one. Hoping someone can help.

**Comment by MalekBouba** [comment]
This is my metro config:

```
const { getDefaultConfig } = require("@expo/metro-config");

const config = getDefaultConfig(__dirname);

// Remove all console logs in production...
config.transformer.minifierConfig.compress.drop_console = true;

config.transformer.babelTransformerPath = require.resolve(
  "react-native-svg-transformer"
);
config.resolver.assetExts = config.resolver.assetExts.filter(
  (ext) => ext !== "svg"
);
config.resolver.sourceExts.push("svg");

module.exports = config;
```
I still having issues only when using:
```
eas build -p android ...
// or
eas build -p ios ...
```
but, when I use:
```
expo build:android ...
// or
expo build:ios ...
```
evrything goes as it should.
**-> I guess there are an inner difference between the two builders.**

the error: (PS: I added an ErrorBoundary to catch it on prod)
![Simulator Screen Shot - iPad (9th generation) - 2022-01-09 at 07 05 47](https://user-images.githubusercontent.com/22925467/148671535-09506f67-7710-4bdd-a1ea-77fc43f97fa6.png)
